### ISSUE TITLE
Raspberry Pi ./install.sh

### ISSUE THREAD

**Issue by Rustymage** [Miosame/flatline#10]
This does not appear to work out the box with Raspberry Pi 4 on buster

```
@SwordPi:~/flatline $ ./install.sh 
mysql uses an image, skipping
nginx uses an image, skipping
Building scraper
Step 1/7 : FROM node:10-jessie
 ---> 304d2488f86a
Step 2/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 3008703a4110
Step 3/7 : COPY package*.json ./
 ---> Using cache
 ---> ebaa0a027b80
Step 4/7 : RUN apt-get update && apt-get install -y nmap net-tools
 ---> Using cache
 ---> 744b554e4d55
Step 5/7 : RUN npm install
 ---> Using cache
 ---> c44cae1a6bba
Step 6/7 : COPY . .
 ---> Using cache
 ---> 73d3c67b4fd5
Step 7/7 : CMD [ "node", "scraper.js" ]
 ---> Using cache
 ---> 590af32dab44

Successfully built 590af32dab44
Successfully tagged flatline_scraper:latest
Building php
Step 1/6 : FROM php:7.2.15-fpm-stretch
 ---> 78d16831d7d1
Step 2/6 : WORKDIR /usr/share/nginx/html
 ---> Using cache
 ---> fa525dd4f70e
Step 3/6 : RUN apt-get update
 ---> Using cache
 ---> 41e6d760455f
Step 4/6 : RUN docker-php-ext-install pdo_mysql
 ---> Using cache
 ---> 9894c663a986
Step 5/6 : RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
 ---> Using cache
 ---> 77fae54da009
Step 6/6 : COPY ./html .
 ---> a001aa4d907c

Successfully built a001aa4d907c
Successfully tagged flatline_php:latest
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
standard_init_linux.go:211: exec user process caused "exec format error"
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
```

I'll be looking later at `ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`. From my brief check out this morning it appears mysql does not play nice on RPi. I might see if I can create an SQL container on another device to see if it works.

Thanks

Rusty

**Comment by Miosame** [comment]
It seems there's indeed no ARM image on docker packaged mysql from what I can tell, but I'm absolutely certain that I had mysql itself running on raspis just fine, so probably https://github.com/Miosame/flatline/issues/7 would apply again, where an external database running on the same host is necessary.

I've also found that mariaDB seems to have full ARM support: https://hub.docker.com/_/mariadb

> ARMv6 32-bit (arm32v6): https://hub.docker.com/u/arm32v6/
> ARMv7 32-bit (arm32v7): https://hub.docker.com/u/arm32v7/
> ARMv8 64-bit (arm64v8): https://hub.docker.com/u/arm64v8/

**Before the next part:**
- please make sure none of the flatline containers are running, `docker-compose down` inside the flatline folder will make sure of it.
- ideally after that, remove the old flatline folder and pull a fresh copy

After that is done; What you could try is if it'll work if you change following line:

https://github.com/Miosame/flatline/blob/cbc1bea088942c508a807056320efc10fff4f89d/docker-compose.yml#L27

to be `image: mariadb:latest` (be sure to keep the _spaces_ the same, since docker-compose is sensitive to those) and then re-run the bootstrap script, to see if that solves it entirely.

MariaDB _should_ be a drop-in replacement anyway (even the docker environment syntax is the same), so if that checks out, then I could test it upstream if it breaks anything - if not, just merge it as the go-to database.

**Comment by Rustymage** [comment]
Small update - Mariadb doesn't have an ARMv7 container. It brings up this error:

```
pi@SwordPi:~/flatline $ docker pull mariadb:latest
latest: Pulling from library/mariadb
no matching manifest for linux/arm/v7 in the manifest list entries
```

A quick Google and Docker link [https://success.docker.com/article/manifest-not-found-for-dtr-image-tag](url) results in this:
```
pi@SwordPi:~/flatline $ docker info  -f '{{.OSType}}/{{.Architecture}}'
linux/armv7l
```
I dropped in this container from Linuxserver [https://hub.docker.com/r/linuxserver/mariadb/](url) & got the following errors:

```
Creating flatline_mysql_1 ... done
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Pulling nginx (nginx:1.14.2-alpine)...
1.14.2-alpine: Pulling from library/nginx
9d34ec1d9f3e: Pull complete
6de085e5117e: Pull complete
e2b0778b765a: Pull complete
a50d0f91cc50: Pull complete
Digest: sha256:485b610fefec7ff6c463ced9623314a04ed67e3945b9c08d7e53a47f6d108dc7
Status: Downloaded newer image for nginx:1.14.2-alpine
flatline_mysql_1 is up-to-date
Creating flatline_php_1     ... done
Creating flatline_scraper_1 ... done
Creating flatline_nginx_1   ... done

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'flatlineUSR'@'flatline_php_1.flatline_default' (using password: YES) (SQL: select * from information_schema.tables where table_schema = flatline and table_name = migrations and table_type = 'BASE TABLE')

  at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'flatlineUSR'@'flatline_php_1.flatline_default' (using password: YES)")
      /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=mysql;port=3306;dbname=flatline", "flatlineUSR", "XXX", [])
      /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.
```

I'm going to remove the flatline folder and start again, then I'm kind of stuck as your comment on external database doesn't appear to be ready for prime time...

I'll report back on reinstall progress soon.

:)

**Comment by Rustymage** [comment]
Fresh ./install.sh & this occurs:

```
Package manifest generated successfully.
standard_init_linux.go:211: exec user process caused "exec format error"
Starting flatline_mysql_1 ... done
flatline_mysql_1 is up-to-date
Starting flatline_scraper_1 ... done
Recreating flatline_php_1   ... done
Recreating flatline_nginx_1 ... done
Migration table not found.
Migration table created successfully.
Migrating: 2020_01_13_194743_create_nodes_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `nodes` add unique `nodes_ipaddr4_unique`(`ipaddr4`))

  at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673| 

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:463

  2   PDOStatement::execute()
      /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:463

  Please use the argument -v to see more details.
```

**Comment by Miosame** [comment]
@Rustymage the last logs you posted, with what image were those? with mariadb or something else

**Comment by Rustymage** [comment]
> @Rustymage the last logs you posted, with what image were those? with mariadb or something else

```
pi@SwordPi:~/flatline $ cat docker-compose.yml 
version: '3.7'

services:
  nginx:
    image: nginx:1.14.2-alpine
    volumes:
      - ./php-mysql-image/html:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
  scraper:
    build: ./nodejs-scraper
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SCAN_RANGE: ${SCAN_RANGE}
      SCAN_INTERVAL: ${SCAN_INTERVAL}
      DB_PORT: ${DB_PORT_CUSTOM}
    network_mode: host
    depends_on:
      - mysql
  mysql:
    image: linuxserver/mariadb
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${DB_PORT_CUSTOM}:3306"
  php:
    build: ./php-mysql-image
    ports:
      - "9000"
    volumes:
      - ./php-mysql-image/html:/usr/share/nginx/html
    depends_on:
      - mysql
```
